import { useState, useCallback } from "react";
import type { NextPage } from "next";
import Head from "next/head";

import styles from "../styles/Home.module.css";
import Header from "../components/header";
import Footer from "../components/footer";
import Banner from "../components/banner";
import Card from "../components/card";
import Modal from "../components/modal";
import Signup from "../components/signup";

const Home: NextPage = () => {
  const [modalOpen, setModalOpen] = useState(false);
  const closeModal = useCallback(() => setModalOpen(false), []);

  return (
    <div className={styles.container}>
      <Head>
        <title>Spacely Space Corp</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Modal isOpen={modalOpen} closeModal={closeModal}>
        <Signup closeModal={closeModal} />
      </Modal>
      <Header link="contact" href="/contact" />
      <main className={styles.main}>
        <Banner
          title="Equal opportunity for space flight, with a spaceship for everyone"
          buttons={[
            {
              label: "Subscribe for updates",
              action: () => setModalOpen(true),
            },
            {
              label: "Find out more",
              link: "https://thejetsons.fandom.com/wiki/Spacely_Space_Sprockets,_Inc.",
            },
          ]}
        />
        <div className={styles.grid}>
          <Card
            image="https://static.wikia.nocookie.net/thejetsons/images/0/0e/Spacely_Space_Spookets_Ep_1.png/revision/latest/scale-to-width-down/256?cb=20190724141056"
            title="News article 1"
          >
            Lorem ipsum dolor sit amet, consectetur adipiscing elit. Quisqueut
            lorem a ligula porttitor accumsan in vel purus.
          </Card>
          <Card
            image="https://static.wikia.nocookie.net/thejetsons/images/b/bd/Spacely_Space_INC.jpg/revision/latest/scale-to-width-down/256?cb=20121217161243"
            title="News article 2"
          >
            Lorem ipsum dolor sit amet, consectetur adipiscing elit. Quisqueut
            lorem a ligula porttitor accumsan in vel purus.
          </Card>
          <Card
            image="https://static.wikia.nocookie.net/thejetsons/images/2/22/Spacely_Sprockets_The_Jetsons_%26_WWE_Robo-WrestleMania_%2817%29.png/revision/latest/scale-to-width-down/256?cb=20200807150337"
            title="News article 3"
          >
            Lorem ipsum dolor sit amet, consectetur adipiscing elit. Quisqueut
            lorem a ligula porttitor accumsan in vel purus.
          </Card>
        </div>
      </main>
      <Footer />
    </div>
  );
};

export default Home;
